_target_: deepchopper.models.basic_module.TokenClassificationLit

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00002
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: deepchopper.models.llm.caduceus.TokenClassificationModule
  number_of_classes: 2
  backbone_name: "caduceus-ph_seqlen-131k_d_model-256_n_layer-16"
  # backbone_name: "caduceus-ps_seqlen-131k_d_model-256_n_layer-16"
  head:
    _target_: deepchopper.models.llm.TokenClassificationHead
    input_size: 256
    # input_size: 512
    lin1_size: 1024
    lin2_size: 1024
    num_class: 2
    use_identity_layer_for_qual: true
    use_qual: true

criterion:
  _target_: deepchopper.models.basic_module.ContinuousIntervalLoss
  lambda_penalty: 0

# compile model for faster training with pytorch 2.0
compile: false
