_target_: deepchopper.models.basic_module.TokenClassificationLit

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: deepchopper.models.cnn.BenchmarkCNN
  number_of_classes: 2
  vocab_size: 11
  num_filters: [128, 256, 512]
  filter_sizes: [7, 9, 11]
  embedding_dim: 100

criterion:
  _target_: deepchopper.models.basic_module.ContinuousIntervalLoss
  lambda_penalty: 0

# compile model for faster training with pytorch 2.0
compile: false
