_target_: deepchopper.models.basic_module.TokenClassificationLit

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: deepchopper.models.transformer.TokenClassificationModule
  vocab_size: 11
  number_of_classes: 2
  d_model: 256
  nhead: 4
  num_encoder_layers: 6
  dim_feedforward: 512

# compile model for faster training with pytorch 2.0
compile: false
